//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Console_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Console_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Console.Console.Resources", typeof(Console_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   You want to add another student? yes or no.
        /// </summary>
        internal static string AddAnotherStudent {
            get {
                return ResourceManager.GetString("AddAnotherStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     1- Add Student.
        /// </summary>
        internal static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   The Student has been deleted correctly..
        /// </summary>
        internal static string DeletedStudent {
            get {
                return ResourceManager.GetString("DeletedStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     5- Delete Student.
        /// </summary>
        internal static string DeleteStudent {
            get {
                return ResourceManager.GetString("DeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   An error has ocurred..
        /// </summary>
        internal static string ErrorControl {
            get {
                return ResourceManager.GetString("ErrorControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     6- Exit the application.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Choose in which format you want:.
        /// </summary>
        internal static string FormatFile {
            get {
                return ResourceManager.GetString("FormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     2- Get All Students.
        /// </summary>
        internal static string GetAllStudents {
            get {
                return ResourceManager.GetString("GetAllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     3- Get Student By Id.
        /// </summary>
        internal static string GetStudentById {
            get {
                return ResourceManager.GetString("GetStudentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Introduce the StudentId of the Student that you want to modify:.
        /// </summary>
        internal static string IntroduceTheStudentToModify {
            get {
                return ResourceManager.GetString("IntroduceTheStudentToModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Invalid Option!.
        /// </summary>
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     2- Json.
        /// </summary>
        internal static string JsonFormat {
            get {
                return ResourceManager.GetString("JsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Choose the option you want:.
        /// </summary>
        internal static string OptionChoose {
            get {
                return ResourceManager.GetString("OptionChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    The Student that you added is:.
        /// </summary>
        internal static string PrintAddStudent {
            get {
                return ResourceManager.GetString("PrintAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This are all the students:.
        /// </summary>
        internal static string PrintAllStudents {
            get {
                return ResourceManager.GetString("PrintAllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This Student is going to be eliminated, are you sure? y/n.
        /// </summary>
        internal static string PrintDeleteStudent {
            get {
                return ResourceManager.GetString("PrintDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   The Student that you search is:.
        /// </summary>
        internal static string PrintFoundStudent {
            get {
                return ResourceManager.GetString("PrintFoundStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Student Modified is:.
        /// </summary>
        internal static string PrintStudentModified {
            get {
                return ResourceManager.GetString("PrintStudentModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     6- Return to Menu of the Format..
        /// </summary>
        internal static string ReturnToFormatMenu {
            get {
                return ResourceManager.GetString("ReturnToFormatMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter the Birthday of the Student:.
        /// </summary>
        internal static string StudentBirthday {
            get {
                return ResourceManager.GetString("StudentBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter Student Id:.
        /// </summary>
        internal static string StudentId {
            get {
                return ResourceManager.GetString("StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter the Name of the Student:.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter the Surname of the Student:.
        /// </summary>
        internal static string StudentSurname {
            get {
                return ResourceManager.GetString("StudentSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please introduce yes or no.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     1- Txt.
        /// </summary>
        internal static string TxtFromat {
            get {
                return ResourceManager.GetString("TxtFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     4- Update Student .
        /// </summary>
        internal static string UpdateStudent {
            get {
                return ResourceManager.GetString("UpdateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     3- Xml.
        /// </summary>
        internal static string XmlFormat {
            get {
                return ResourceManager.GetString("XmlFormat", resourceCulture);
            }
        }
    }
}
